# Profil de développement avec H2
spring:
  datasource:
    url: jdbc:h2:mem:consoledb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.megatim.iso20022: DEBUG
    org.hibernate.SQL: DEBUG
