# Profil de production avec PostgreSQL
server:
  servlet:
    context-path: /
  forward-headers-strategy: framework

app:
  base-url: ${RAILWAY_PUBLIC_DOMAIN:http://localhost:8080}
  api-docs: /v3/api-docs
  swagger-ui: /swagger-ui.html
  actuator: /actuator
  h2-console: /h2-console

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

logging:
  level:
    com.megatim.iso20022: INFO
    org.hibernate.SQL: WARN
  file:
    name: logs/console-log-api.log
    max-size: 10MB
    max-history: 30

  h2:
    console:
      enabled: false
