name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/iso20022-console-log
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -ntp clean verify

      - name: Run tests
        run: mvn -B test

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-railway:
    name: Deploy to Railway
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/iso20022-console-log:${{ github.sha }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }} # ton service Railway
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_PROFILES_ACTIVE: prod

    steps:
      - uses: actions/checkout@v4

      - name: Set Railway environment variables
        run: |
          railway variables set IMAGE=$IMAGE --service $SVC_ID
          railway variables set SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL --service $SVC_ID
          railway variables set SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME --service $SVC_ID
          railway variables set SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD --service $SVC_ID
          railway variables set SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE --service $SVC_ID

      - name: Deploy to Railway
        run: railway up --service=$SVC_ID --detach